# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: routecontrol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import routecontrol_types_pb2 as routecontrol__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='routecontrol.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12routecontrol.proto\x1a\x18routecontrol_types.proto2K\n\x0cRouteControl\x12;\n\nSendupdate\x12\x14.routecontrol.Update\x1a\x17.routecontrol.UpdateAckb\x06proto3'
  ,
  dependencies=[routecontrol__types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ROUTECONTROL = _descriptor.ServiceDescriptor(
  name='RouteControl',
  full_name='RouteControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=48,
  serialized_end=123,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sendupdate',
    full_name='RouteControl.Sendupdate',
    index=0,
    containing_service=None,
    input_type=routecontrol__types__pb2._UPDATE,
    output_type=routecontrol__types__pb2._UPDATEACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTECONTROL)

DESCRIPTOR.services_by_name['RouteControl'] = _ROUTECONTROL

# @@protoc_insertion_point(module_scope)
