# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import routecontrol_types_pb2 as routecontrol__types__pb2


class RouteControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Sendupdate = channel.unary_unary(
                '/RouteControl/Sendupdate',
                request_serializer=routecontrol__types__pb2.Update.SerializeToString,
                response_deserializer=routecontrol__types__pb2.UpdateAck.FromString,
                )


class RouteControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Sendupdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RouteControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Sendupdate': grpc.unary_unary_rpc_method_handler(
                    servicer.Sendupdate,
                    request_deserializer=routecontrol__types__pb2.Update.FromString,
                    response_serializer=routecontrol__types__pb2.UpdateAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RouteControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RouteControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Sendupdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RouteControl/Sendupdate',
            routecontrol__types__pb2.Update.SerializeToString,
            routecontrol__types__pb2.UpdateAck.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
