# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exabgpapi.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import gobgp_pb2 as gobgp__pb2
import attribute_pb2 as attribute__pb2
import capability_pb2 as capability__pb2
import exabgp_pb2 as exabgp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='exabgpapi.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x65xabgpapi.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0bgobgp.proto\x1a\x0f\x61ttribute.proto\x1a\x10\x63\x61pability.proto\x1a\x0c\x65xabgp.proto2\xcc\x02\n\texabgpapi\x12?\n\rSendPeerState\x12\x16.gobgpapi.ExaPeerState\x1a\x16.google.protobuf.Empty\x12=\n\x0cSendPeerOpen\x12\x15.gobgpapi.ExaPeerOpen\x1a\x16.google.protobuf.Empty\x12\x43\n\x11SendPeerKeepalive\x12\x16.gobgpapi.ExaKeepalive\x1a\x16.google.protobuf.Empty\x12?\n\rSendUpdateEoR\x12\x16.gobgpapi.ExaUpdateEoR\x1a\x16.google.protobuf.Empty\x12\x39\n\nSendUpdate\x12\x13.gobgpapi.ExaUpdate\x1a\x16.google.protobuf.Emptyb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,gobgp__pb2.DESCRIPTOR,attribute__pb2.DESCRIPTOR,capability__pb2.DESCRIPTOR,exabgp__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_EXABGPAPI = _descriptor.ServiceDescriptor(
  name='exabgpapi',
  full_name='exabgpapi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=171,
  serialized_end=503,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendPeerState',
    full_name='exabgpapi.SendPeerState',
    index=0,
    containing_service=None,
    input_type=exabgp__pb2._EXAPEERSTATE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendPeerOpen',
    full_name='exabgpapi.SendPeerOpen',
    index=1,
    containing_service=None,
    input_type=exabgp__pb2._EXAPEEROPEN,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendPeerKeepalive',
    full_name='exabgpapi.SendPeerKeepalive',
    index=2,
    containing_service=None,
    input_type=exabgp__pb2._EXAKEEPALIVE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendUpdateEoR',
    full_name='exabgpapi.SendUpdateEoR',
    index=3,
    containing_service=None,
    input_type=exabgp__pb2._EXAUPDATEEOR,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendUpdate',
    full_name='exabgpapi.SendUpdate',
    index=4,
    containing_service=None,
    input_type=exabgp__pb2._EXAUPDATE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXABGPAPI)

DESCRIPTOR.services_by_name['exabgpapi'] = _EXABGPAPI

# @@protoc_insertion_point(module_scope)
